name = "cave-horror"
author = "NeichS"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b15f2cc00ef79e66cd0d6f6df9e496702e694655019446ca091a8ffd653bcb6"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
