name = "cave-horror"
author = "NeichS"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63d6b91db08e71818e90985c0fedd312a04f7f00faddf1bc466ad11afbf060f0"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
