name = "cave-horror"
author = "NeichS"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17b7be706984dbd3389db8128c75257b2995b2c0541f1fae12d4598ed7e7c8f7"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
